app = "microblog-bde2-a"
primary_region = "ord"

[http_service]
auto_start_machines = true
auto_stop_machines = true
min_machines_running = 1

[[services]]
internal_port = 5_000
protocol = "tcp"

  [[services.ports]]
  handlers = [ "http" ]
  port = 80

  [[services.ports]]
  handlers = [ "tls", "http" ]
  port = 443

  [[services.tcp_checks]]
  grace_period = "5s"
  interval = "15s"
  timeout = "2s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1_024
