# fly.toml app configuration file generated for microblog-bde2-a on 2025-05-29T17:09:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'microblog-bde2-a'
primary_region = 'dfw'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[services]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0

[http_service]
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
